CREATE SCHEMA RAW;
GO
CREATE SCHEMA STAGING;
GO
CREATE SCHEMA DWH;
GO

CREATE TABLE RAW.Novedades_Mensuales (
    LUGAR NVARCHAR(255),
    CARGO NVARCHAR(255),
    REGISTRO NVARCHAR(100),
    COLABORADOR NVARCHAR(255),
    L1 NVARCHAR(50), C NVARCHAR(50), M NVARCHAR(50), D NVARCHAR(50), P NVARCHAR(50), F NVARCHAR(50),
    VALOR_x_HORA NVARCHAR(100),
    SUELDO_FIJO NVARCHAR(100),
    COMISION NVARCHAR(100),
    TOTAL NVARCHAR(100),
    TRANSFERENCIA NVARCHAR(100),
    EFECTIVO NVARCHAR(100),
    HORAS_EXTRA NVARCHAR(100), VALOR_HORAS_EXTRA NVARCHAR(100),
    HORAS_AU NVARCHAR(100), VALOR_HORAS_AU NVARCHAR(100),
    HORAS_FERIADO NVARCHAR(100), VALOR_HORAS_FERIADO NVARCHAR(100),
    BONO_JEFE NVARCHAR(100),
    BONO_DIRECTOR NVARCHAR(100),
    BONO_X_VENTAS NVARCHAR(100),
    AUMENTO NVARCHAR(100), REDONDEO NVARCHAR(100), 
    ADELANTO NVARCHAR(100), PRESTAMO NVARCHAR(100), DESCUENTO NVARCHAR(100)
);
GO

CREATE TABLE STAGING.Historico_Salarios (
    ID_Historia INT IDENTITY(1,1) PRIMARY KEY, 
    Fecha_Periodo DATE NOT NULL,               
    Fecha_Carga DATETIME DEFAULT GETDATE(),    
    LUGAR NVARCHAR(255),
    CARGO NVARCHAR(255),
    REGISTRO NVARCHAR(100),
    COLABORADOR NVARCHAR(255),
    L1 NVARCHAR(50), C NVARCHAR(50), M NVARCHAR(50), D NVARCHAR(50), P NVARCHAR(50), F NVARCHAR(50),
    VALOR_x_HORA NVARCHAR(100),
    SUELDO_FIJO NVARCHAR(100),
    COMISION NVARCHAR(100),
    TOTAL NVARCHAR(100),
    TRANSFERENCIA NVARCHAR(100),
    EFECTIVO NVARCHAR(100),
    HORAS_EXTRA NVARCHAR(100), VALOR_HORAS_EXTRA NVARCHAR(100),
    HORAS_AU NVARCHAR(100), VALOR_HORAS_AU NVARCHAR(100),
    HORAS_FERIADO NVARCHAR(100), VALOR_HORAS_FERIADO NVARCHAR(100),
    BONO_JEFE NVARCHAR(100),
    BONO_DIRECTOR NVARCHAR(100),
    BONO_X_VENTAS NVARCHAR(100),
    AUMENTO NVARCHAR(100), REDONDEO NVARCHAR(100), 
    ADELANTO NVARCHAR(100), PRESTAMO NVARCHAR(100),
    DESCUENTO NVARCHAR(100)
);
GO