CREATE OR ALTER   PROCEDURE [STAGING].[sp_Procesar_Mes]
    @FechaDelMes DATE  
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO STAGING.Historico_Salarios (
        Fecha_Periodo, 
        LUGAR, CARGO, REGISTRO, COLABORADOR,
        L1, C, M, D, P, F,
        VALOR_x_HORA, SUELDO_FIJO, COMISION, TOTAL,
        TRANSFERENCIA, EFECTIVO,
        HORAS_EXTRA, VALOR_HORAS_EXTRA,
        HORAS_AU, VALOR_HORAS_AU,
        HORAS_FERIADO, VALOR_HORAS_FERIADO,
        BONO_JEFE, BONO_DIRECTOR, BONO_X_VENTAS,
        AUMENTO, REDONDEO, ADELANTO, PRESTAMO, DESCUENTO
    )
    SELECT 
        @FechaDelMes, 
        LUGAR, CARGO, REGISTRO, COLABORADOR,
        L1, C, M, D, P, F,
        VALOR_x_HORA, SUELDO_FIJO, COMISION, TOTAL,
        TRANSFERENCIA, EFECTIVO,
        HORAS_EXTRA, VALOR_HORAS_EXTRA,
        HORAS_AU, VALOR_HORAS_AU,
        HORAS_FERIADO, VALOR_HORAS_FERIADO,
        BONO_JEFE, BONO_DIRECTOR, BONO_X_VENTAS,
        AUMENTO, REDONDEO, ADELANTO, PRESTAMO, DESCUENTO
    FROM RAW.Novedades_Mensuales;

    
    TRUNCATE TABLE RAW.Novedades_Mensuales;

    PRINT 'Proceso completado para fecha: ' + CAST(@FechaDelMes AS NVARCHAR(20));
END;
